// DEFAULT TYPE
export interface IAction {
  type: string;
}

export type InferValueTypes<T> = T extends { [key: string]: infer U } ? U : never;

// ERROR CONSTANTS
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const CLEAR_MAIN_ERROR = 'CLEAR_MAIN_ERROR';
export const CLEAR_PLAN_ERROR = 'CLEAN_PLAN_ERROR';
export const CLEAR_TASK_ERROR = 'CLEAR_TASK_ERROR';
export const CLEAR_ALL_ERRORS = 'CLEAR_ALL_ERRORS';

// AUTH CONSTANTS
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';
export const CREATE_USER = 'CREATE_USER';

// DATA
export const SAVE_EDIT_PLAN = 'SAVE_EDIT_PLAN';

// PLANS CONSTANTS
export const DOWNLOAD_PLANS = 'DOWNLOAD_PLANS';
export const DOWNLOAD_PLANS_SUCCESS = 'DOWNLOAD_PLANS_SUCCESS';
export const DOWNLOAD_PLANS_FAILED = 'DOWNLOAD_PLAN_FAILED';

export const CREATE_PLAN = 'CREATE_PLAN';
export const CREATE_PLAN_SUCCESS = 'CREATE_PLAN_SUCCESS';
export const CREATE_PLAN_FAILED = 'CREATE_PLAN_FAILED';

export const REMOVE_PLAN = 'REMOVE_PLAN';
export const REMOVE_PLAN_SUCCESS = 'REMOVE_PLAN_SUCCESS';
export const REMOVE_PLAN_FAILED = 'REMOVE_PLAN_FAILED';

export const EDIT_PLAN = 'EDIT_PLAN';
export const EDIT_PLAN_SUCCESS = 'EDIT_PLAN_SUCCESS';
export const EDIT_PLAN_FAILED = 'EDIT_PLAN_FAILED';

// TASKS CONSTANTS
export const DOWNLOAD_TASKS = 'DOWNLOAD_TASKS';
export const DOWNLOAD_TASKS_SUCCESS = 'DOWNLOAD_TASKS_SUCCESS';
export const DOWNLOAD_TASKS_FAILED = 'DOWNLOAD_TASKS_FAILED';

export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILED = 'CREATE_TASK_FAILED';

export const REMOVE_TASK = 'REMOVE_TASK';
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS';
export const REMOVE_TASK_FAILED = 'REMOVE_TASK_FAILED';

export const EDIT_TASK = 'EDIT_TASK';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const EDIT_TASK_FAILED = 'EDIT_TASK_FAILED';